CREATE DATABASE IF NOT EXISTS `active`;
USE `active`;
SET TIME_ZONE='-05:00';

DROP TABLE IF EXISTS `facility_type`;
DROP TABLE IF EXISTS `language_translation`;
DROP TABLE IF EXISTS `availability`;
DROP TABLE IF EXISTS `facility_hours`;
DROP TABLE IF EXISTS `facility_branch`;
DROP TABLE IF EXISTS `activity`;
DROP TABLE IF EXISTS `type`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `facility`;
DROP TABLE IF EXISTS `city`;
DROP TABLE IF EXISTS `address`;
DROP TABLE IF EXISTS `translation`;
DROP TABLE IF EXISTS `language`;

--
-- Table structure for table `language`
--
CREATE TABLE `language` (
  `ID` char(2),
  `TITLE` varchar(45) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `translation`
--
CREATE TABLE `translation` (
  `ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `city`
--
CREATE TABLE `city` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(45) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `address`
--
CREATE TABLE `address` (
  `ID` int NOT NULL,
  `STREET_TRANSLATION_ID` int NOT NULL,
  `CITY` varchar(45) NOT NULL,
  `PROVINCE` varchar(45) NOT NULL,
  `POSTAL_CODE` char(6) NOT NULL,
  `COUNTRY` varchar(45) NOT NULL,
  `LONGITUDE` decimal(12,10) NOT NULL,
  `LATITUDE` decimal(12,10) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `STREET_TRANSLATION_ID` (`STREET_TRANSLATION_ID`),
  CONSTRAINT `ADDRESS_ibfk_1` FOREIGN KEY (`STREET_TRANSLATION_ID`) REFERENCES `translation` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `facility`
--
CREATE TABLE `facility` (
  `ID` int NOT NULL,
  `PHONE` varchar(12) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `TITLE_TRANSLATION_ID` int NOT NULL,
  `ADDRESS_ID` int NOT NULL,
  `URL_TRANSLATION_ID` int NOT NULL,
  `CITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `TITLE_TRANSLATION_ID` (`TITLE_TRANSLATION_ID`),
  KEY `ADDRESS_ID` (`ADDRESS_ID`),
  KEY `URL_TRANSLATION_ID` (`URL_TRANSLATION_ID`),
  KEY `CITY_ID` (`CITY_ID`),
  CONSTRAINT `FACILITY_ibfk_1` FOREIGN KEY (`TITLE_TRANSLATION_ID`) REFERENCES `translation` (`ID`),
  CONSTRAINT `FACILITY_ibfk_2` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `address` (`ID`),
  CONSTRAINT `FACILITY_ibfk_3` FOREIGN KEY (`URL_TRANSLATION_ID`) REFERENCES `translation` (`ID`),
  CONSTRAINT `FACILITY_ibfk_4` FOREIGN KEY (`CITY_ID`) REFERENCES `city` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `category`
--
CREATE TABLE `category` (
  `ID` int NOT NULL,
  `TITLE_TRANSLATION_ID` int NOT NULL,
  `CITY_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `TITLE_TRANSLATION_ID` (`TITLE_TRANSLATION_ID`),
  KEY `CITY_ID` (`CITY_ID`),
  CONSTRAINT `CATEGORY_ibfk_1` FOREIGN KEY (`TITLE_TRANSLATION_ID`) REFERENCES `translation` (`ID`),
  CONSTRAINT `CATEGORY_ibfk_2` FOREIGN KEY (`CITY_ID`) REFERENCES `city` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `type`
--
CREATE TABLE `type` (
  `ID` int NOT NULL,
  `CATEGORY_ID` int NOT NULL,
  `TITLE_TRANSLATION_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  KEY `TITLE_TRANSLATION_ID` (`TITLE_TRANSLATION_ID`),
  CONSTRAINT `TYPE_ibfk_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `category` (`ID`),
  CONSTRAINT `TYPE_ibfk_2` FOREIGN KEY (`TITLE_TRANSLATION_ID`) REFERENCES `translation` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `activity`
--
CREATE TABLE `activity` (
  `ID` int NOT NULL,
  `TYPE_ID` int NOT NULL,
  `TITLE_TRANSLATION_ID` int NOT NULL,
  `MIN_AGE` int,
  `MAX_AGE` int,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `TYPE_ID` (`TYPE_ID`),
  KEY `TITLE_TRANSLATION_ID` (`TITLE_TRANSLATION_ID`),
  CONSTRAINT `ACTIVITY_ibfk_1` FOREIGN KEY (`TYPE_ID`) REFERENCES `type` (`ID`),
  CONSTRAINT `ACTIVITY_ibfk_2` FOREIGN KEY (`TITLE_TRANSLATION_ID`) REFERENCES `translation` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `facility_branch`
--
CREATE TABLE `facility_branch` (
  `ID` char(45) NOT NULL,
  `FACILITY_ID` int NOT NULL,
  `DESCRIPTION` varchar(255),
  `RESERVATION_URL` varchar(255) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FACILITY_ID` (`FACILITY_ID`),
  CONSTRAINT `FACILITY_BRANCH_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `facility` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `availability`
--
CREATE TABLE `availability` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FACILITY_BRANCH_ID` char(45) NOT NULL,
  `ACTIVITY_ID` int NOT NULL,
  `START_TIME` DATETIME NOT NULL,
  `END_TIME` DATETIME,
  `IS_AVAILABLE` tinyint,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FACILITY_BRANCH_ID`,`ACTIVITY_ID`,`START_TIME`),
  KEY `ID` (`ID`),
  CONSTRAINT `AVAILABILITY_ibfk_1` FOREIGN KEY (`FACILITY_BRANCH_ID`) REFERENCES `facility_branch` (`ID`),
  CONSTRAINT `AVAILABILITY_ibfk_2` FOREIGN KEY (`ACTIVITY_ID`) REFERENCES `activity` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `facility_activity`
--
CREATE TABLE `facility_type` (
  `FACILITY_ID` int NOT NULL,
  `TYPE_ID` int NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FACILITY_ID`,`TYPE_ID`),
  CONSTRAINT `FACILITY_TYPE_ibfk_1` FOREIGN KEY (`FACILITY_ID`) REFERENCES `facility` (`ID`),
  CONSTRAINT `FACILITY_TYPE_ibfk_2` FOREIGN KEY (`TYPE_ID`) REFERENCES `type` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `language_translation`
--
CREATE TABLE `language_translation` (
  `TRANSLATION_ID` int NOT NULL,
  `LANGUAGE_ID` char(2) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `LAST_UPDATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TRANSLATION_ID`,`LANGUAGE_ID`),
  CONSTRAINT `LANGUAGE_TRANSLATION_ibfk_1` FOREIGN KEY (`TRANSLATION_ID`) REFERENCES `translation` (`ID`),
  CONSTRAINT `LANGUAGE_TRANSLATION_ibfk_2` FOREIGN KEY (`LANGUAGE_ID`) REFERENCES `language` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;