name: Server Build and Run

on:
  push:
    branches:
      - master

jobs:
  copy_source_code_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Connect to server and copy source code
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "." 
          target: "~/active"

  clean_and_rerun_containers:
    runs-on: ubuntu-latest
    needs: copy_source_code_to_server
  
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
           cd ~/active
           docker compose down
           docker compose up
           
        env:
          API_SERVER_PORT: ${{ secrets.API_SERVER_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          TIME_ZONE: ${{ secrets.TIME_ZONE }}
          
