name: Server Build and Run

on:
  push:
    branches:
      - master

jobs:
  copy_source_code_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Connect to server and copy source code
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "." 
          target: "~/active"

  clean_and_rerun_containers:
    runs-on: ubuntu-latest
    needs: copy_source_code_to_server
  
    steps:
      - name: Connect to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          
      - name: Set up environment variables
        env:
          API_SERVER_PORT: ${{ secrets.API_SERVER_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          TIME_ZONE: ${{ secrets.TIME_ZONE }}
        run: echo "Environment variables are set up"
          
      - name: Stop containers
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "docker stop ${{ secrets.API_SERVER_CONTAINER_NAME }}"
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "docker stop ${{ secrets.SCRAPER_CONTAINER_NAME }}"
      
      - name: Remove containers
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "docker rm ${{ secrets.API_SERVER_CONTAINER_NAME }}"
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "docker rm ${{ secrets.SCRAPER_CONTAINER_NAME }}"

      - name: Build and run containers
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd ~/active && docker-compose up -d"
